<a href="https://colab.research.google.com/github/seoseonho/R_lecture/blob/main/day0628.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#반복문 복습
- for loop and while loop

In [ ]:
for i in range(3):
  print("Hello World")
  print("안녕하세여")

Hello World
안녕하세여
Hello World
안녕하세여
Hello World
안녕하세여


In [ ]:
# "K" in "Kaggle"
if "K" == "a"
print(출력이 안되나여?)

False

In [ ]:
a = "Kaggle"

for i in a:
  print(i)
  if i == "a":
    break
  print("Hello World")
  print("안녕하세여")

- 리스트의 값이 존재
- 존

In [ ]:
numbers = [1, 2, 3, 4, 5]
sum = 0

for num in numbers:
  print("numbers:", num)
  sum = sum + num
  print("total:", sum)

print("----최종 결괏값---")
print(sum)

In [ ]:
fruits = ['apple', 'kiwi', 'mango']
newlist = []

# apple : a가 있나요? 있네요, newlist에 추가하세요.
# kiwi : a가 있나요? 없네요. 그럼 넘어가요
# mango : a가 있나요? 있네요. newlist에 추가하세요.
for fruit in fruits:
  print("조건문 밖 :", fruit)
  if "a" in fruit:
    print("조건문 안쪽 :", fruit)
    newlist.append(fruit)

print(newlist)

조건문 밖 : apple
조건문 안쪽 : apple
조건문 밖 : kiwi
조건문 밖 : mango
조건문 안쪽 : mango
['apple', 'mango']


### While Loop

while문 : 분석할 때? 거의 쓸일이 없음

In [ ]:
i = 1
while i < 10: #참일때만 반복문 코드가 돔
  # 코드
  print(i) 
  i += 1 # 1씩 증감
   #i -= 1 # 1씩 감소

1
2
3
4
5
6
7
8
9


## 사용자 정의 함수
- 내가 필요에 의해 직접 함수를 작성
- 

In [ ]:
def 함수명(param1, param2):
  #코드
  return None

In [ ]:
def add(a = 0, b = 1):
  c = a+b
  return a + b

print(add(a = 5, b =4))
print(add())

9
1


-사칙연산 사용자 정의 함수 만들기
- 함수 문서화
  + 키워드 : Docstring

In [ ]:
def seo(a , b ):
  """a, b를 더하는 함수

  parameters:
  a (int): int형 숫자 a가 입력

  b (int): int형 숫자 b가 입력

  Returns:
    int : 반환값

  """
  return a - b
  
print(seo(a = 1,b = 6))
print(seo.__doc__)

## Numpy
- 내장 모듈(=라이브러리=패키지)
(x)
- 별도 라이브러리 설치 필요

In [26]:
import numpy as np
print(np.__version__)

1.21.6


In [ ]:
tepm = [1, 2, 3,]
tepm_array = np.array(temp) # 리스트에서 배열로 변환

print(type(tepm))
print

##사칙연산


In [28]:
math_score = [90, 80 ,100]
eng_score = [80, 90 ,100]

# math_score + eng_score
math_array = np. array(math_score)
eng_array = np. array(eng_score)

total = math_array + eng_array
print(total)
print(type(total))

[170 170 200]
<class 'numpy.ndarray'>


# 집계함

In [30]:
print(np.min(total))
print(np.max(total))
print(np.sum(total))

170
200
540


# 차원 확인
-배열의 차운 확인 필요

In [ ]:
# 1차원 배열 생성
temp_arr = np.array([1, 2, 3])
print(temp_arr.shape)
print(temp_arr.ndim)

(3,)
1


In [ ]:
# 2차원 배열 생섬
temp_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(temp_arr.shape)
print(temp_arr. ndim)
print(temp_arr)

(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [37]:
# 3차원 배열 -> 이미지
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10 ,11 ,12]]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(2, 2, 3)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
temp_arr = np.zeros((3, 3, 3))
temp_arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

- 모두 1로 채운다


In [ ]:
temp_arr = np.ones((2,3))
temp_arr

- 임의의 산수값으로 채운다.


In [34]:
temp_arr = np.full((3,3), 100)
temp_arr

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

- 최소, 최대 숫자의 범위를 정해두고, 각 구간별로 값을 생성

In [35]:
temp_arr = np.linspace(5, 10, 10)
temp_arr

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

- 반복문 시, 자주 등장하는 배

In [36]:
temp_arr = np.arange(1, 11, 1)
temp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 난수 새성


In [10]:
from numpy import random
x = random.rand()
print(x)

0.7302033222515089


In [11]:
import numpy
x = numpy . random. rand()
print(x)

0.20947760824145267


- 랜덤 정수값 추출

In [14]:
from numpy import random
x = random.randint(100, size = (5))
print(x)
print(type(x))

[20 29 24 33 17]
<class 'numpy.ndarray'>


- 랜덤 배열, 실수값 추출

In [15]:
from numpy import random
x = random.rand(2, 5)
print(x)
print(type(x))

[[0.1334899  0.57181872 0.55790487 0.91432572 0.58810285]
 [0.71250157 0.242012   0.15704999 0.71087509 0.12661234]]
<class 'numpy.ndarray'>


## Numpy 사칙 연

In [16]:
import numpy as np
array_01 = np.array([1, 2, 3])
array_02 = np. array([10, 20, 30])

In [ ]:
# 덧셈
newArr = np.add(array_01, array_02)
print(newArr)


## 소수점 정렬
-소수점을 정렬하는 다양한 방

In [19]:
import numpy as np
temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
[-1.  1.]


In [22]:
# 임의의 소숫점 자리에서 반올림
temp_arr = np.around([-1.23454435345, 1.234532525], 5)
print(temp_arr)

[-1.23454  1.23453]


In [23]:
#  소숫점 모두 내림
temp_arr = np.floor([-1.23454435345, 1.234532525])
print(temp_arr)

[-1.23454  1.23453]


In [25]:
#  소숫점 모두 올림
temp_arr = np.ceil([-1.23454435345, 1.234532525])
print(temp_arr)

[-1.  2.]


## 조건식
- pandas 가공
- numpy
-조건식 
  + 하나의 조건식 = np.arange(10)
  + 다중 조건식

In [39]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# 5보다 작으면 원 값 유지
# 5보다 크면 곱하기 10을 해줌

In [42]:
# np. where(조건식, 참일 때, 거짓일 때)
np.where(temp_arr < 5, temp_arr, temp_arr * 10)


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [47]:
temp_arr = np.arange(100)
# temp_arr
cond_list = [temp_arr >5, temp_arr <2]
choice_list = [temp_arr *2, temp_arr + 100]

# np.select(조건식 리스트, 결괏값 리스트, default =)
np.select(cond_list, choice_list, default = temp_arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

## Reshape
-배열의 차원 또는 크기를
바꾼다.
- 곱셈만 할줄 알면 끝.

In [50]:
import numpy as np
temp_array = np.ones((3, 4))
print(temp_array.shape)
print(temp_array)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [52]:
after_reshape = temp_array.reshape(1, 12)
print(after_reshape.shape)
print(after_reshape)

(1, 12)
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [58]:
after_reshape = temp_array.reshape(2, 2, 3)
print(after_reshape.shape)
print(after_reshape)

(2, 2, 3)
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [61]:
after_reshape = temp_array.reshape(2, -1)
print(after_reshape.shape)
print(after_reshape)

(2, 6)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


# pandas 튜토리

In [63]:
import pandas as pd
print(pd.__version__)

1.3.5


In [64]:
temp_dict = {
    'col1' : [1, 2],
    'col2' : [3 ,4]
}

df =pd.DataFrame(temp_dict)
print(df)
print(type(df))

   col1  col2
0     1     3
1     2     4
<class 'pandas.core.frame.DataFrame'>


## 구글 드라이브 연동


In [66]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [72]:
DATA_PATH ='/content/drive/MyDrive/Colab Notebooks/human_AI/Basic/Chapter 3. pandas/data/'
lemonade = pd.read_csv(DATA_PATH + 'Lemonade2016.csv')
# covid df = pd.read_csv(DATA_PATH + 'owid-covid-data.csv')

lemonade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         31 non-null     object 
 1   Location     32 non-null     object 
 2   Lemon        32 non-null     int64  
 3   Orange       32 non-null     int64  
 4   Temperature  32 non-null     int64  
 5   Leaflets     31 non-null     float64
 6   Price        32 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.9+ KB
